[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"
authors = ["Ikuya Yamada <dalyson.roman34@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.7" }
worker-macros = { version = "0.7" }
